services:
  rabbitmq: 
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  orchestrator:
    build:
      dockerfile: dev.Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
    - 8080:8080
    depends_on:
      - rabbitmq